package com.erpl.employee.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-10-05T16:45:18.543+05:30
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "QueryEmployeeIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryEmployeeIn {

    @WebMethod(operationName = "FindByIdentification", action = "http://sap.com/xi/A1S/Global/QueryEmployeeIn/FindByIdentificationRequest")
    @WebResult(name = "EmployeeDataByIdentificationResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "EmployeeDataByIdentificationResponse_sync")
    public EmployeeDataSimpleByResponseMessageSync findByIdentification(

        @WebParam(partName = "EmployeeDataByIdentificationQuery_sync", name = "EmployeeDataByIdentificationQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        EmployeeDataSimpleByQueryMessageSync employeeDataByIdentificationQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "FindBasicDataByIdentification", action = "http://sap.com/xi/A1S/Global/QueryEmployeeIn/FindBasicDataByIdentificationRequest")
    @WebResult(name = "EmployeeBasicDataByIdentificationResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "EmployeeBasicDataByIdentificationResponse_sync")
    public EmployeeBasicDataResponseMessageSync findBasicDataByIdentification(

        @WebParam(partName = "EmployeeBasicDataByIdentificationQuery_sync", name = "EmployeeBasicDataByIdentificationQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        EmployeeBasicDataByIdentificationQueryMessageSync employeeBasicDataByIdentificationQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "FindBiographicalDataByIdentification", action = "http://sap.com/xi/A1S/Global/QueryEmployeeIn/FindBiographicalDataByIdentificationRequest")
    @WebResult(name = "EmployeeBiographicalDataByIdentificationResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "EmployeeBiographicalDataByIdentificationResponse_sync")
    public EmployeeBiographicalDataResponseMessageSync findBiographicalDataByIdentification(

        @WebParam(partName = "EmployeeBiographicalDataByIdentificationQuery_sync", name = "EmployeeBiographicalDataByIdentificationQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        EmployeeBiographicalDataByIdentificationQueryMessageSync employeeBiographicalDataByIdentificationQuerySync
    ) throws StandardFaultMessage_Exception;
}
