
package com.erpl.employee.wsdl2java;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-10-05T16:45:18.481+05:30
 * Generated source version: 3.5.3
 */

@WebFault(name = "StandardFaultMessage", targetNamespace = "http://sap.com/xi/AP/Common/Global")
public class StandardFaultMessage_Exception extends Exception {

    private com.erpl.employee.wsdl2java.StandardFaultMessage faultInfo;

    public StandardFaultMessage_Exception() {
        super();
    }

    public StandardFaultMessage_Exception(String message) {
        super(message);
    }

    public StandardFaultMessage_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public StandardFaultMessage_Exception(String message, com.erpl.employee.wsdl2java.StandardFaultMessage standardFaultMessage) {
        super(message);
        this.faultInfo = standardFaultMessage;
    }

    public StandardFaultMessage_Exception(String message, com.erpl.employee.wsdl2java.StandardFaultMessage standardFaultMessage, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = standardFaultMessage;
    }

    public com.erpl.employee.wsdl2java.StandardFaultMessage getFaultInfo() {
        return this.faultInfo;
    }
}
